### ISSUE TITLE
Stuck at the rainbow splash screen on RPi2

### ISSUE THREAD

**Issue by hacksterous** [boochow/micropython-raspberrypi#24]
Followed the instructions to the letter -- but stuck at the rainbow splash screen. Looks like
the kernel firmware.img has some problem...

I am building on the Ubuntu sub-system on Windows 10.

I see no error or warnings except this:

source/device/hid/keyboard.c: In function 'KeyboardAttach':
source/device/hid/keyboard.c:163:7: warning: this 'if' clause does not guard... [-Wmisleading-indentation]
       if (parse->Report[i]->Fields[j].Usage.Keyboard >= KeyboardLeftControl
       ^~
source/device/hid/keyboard.c:166:8: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the 'if'
        data->KeyFields[(u16)parse->Report[i]->Fields[j].Usage.Keyboard - (u16)KeyboardLeftControl] =
        ^~~~
LINK build/firmware.elf

**Comment by boochow** [comment]
@hacksterous thank you for reporting this, I can't state where the problem is for now.
Could you try the precompiled binary here:

http://blog.boochow.com/wp-content/uploads/mp-rpi2-20181228-uskbd.zip

Please add bootcode.bin and start.elf. They are not inclueded in the above zip file.

The related blog post is here (I'm sorry it is in Japanese... a url of google translated version follows).

https://blog.boochow.com/article/mp-rpi2-test-release.html

https://translate.google.co.jp/translate?hl=ja&sl=ja&tl=en&u=https%3A%2F%2Fblog.boochow.com%2Farticle%2Fmp-rpi2-test-release.html

**Comment by hacksterous** [comment]
Thanks, that worked!

The USB keyboard does not work -- I see USB keyboard errors still, but anyway that's a good start.

Thanks.
